# Table of Contents
1. [Data Loading](#data-loading)
2. [Data Exploration](#data-exploration)
3. [Data Cleaning](#data-cleaning)
4. [Joining Data Frames](#joining-data-frames)

# Data Loading

In [1]:
#packages 
from pathlib import Path
import pandas as pd

In [2]:
# paths 
project_fldr = Path.cwd().parent
raw_fldr = project_fldr /'Data'/'unprocessed' 
processed_fldr = project_fldr /'Data'/'processed'

In [3]:
# Importing the data
pest_use = pd.read_csv("https://www.sciencebase.gov/catalog/file/get/5e95c12282ce172707f2524e?name=EPest_county_estimates_2013_2017_v2.txt", sep="\t")
site_info = pd.read_csv(
    "https://prod-is-usgs-sb-prod-content.s3.amazonaws.com/6712dadfd34eb6a152fc9907/t1_site_info.txt?AWSAccessKeyId=AKIAI7K4IX6D4QLARINA&Expires=1793148387&Signature=ksQ7Ro9e%2FRAaPgXlOZVTMWaDjis%3D",
    sep=None,
    engine="python",
)
pest_water = pd.read_csv(
    "https://prod-is-usgs-sb-prod-content.s3.amazonaws.com/6712dadfd34eb6a152fc9907/t2_pest_concs.txt?AWSAccessKeyId=AKIAI7K4IX6D4QLARINA&Expires=1793148736&Signature=nXSgtnB3M2UiTnJ3EOYiDyeK0as%3D",
    sep=None,
    engine="python",
)

# Data Exploration

In [4]:
pest_use.head()

,COMPOUND,YEAR,STATE_FIPS_CODE,COUNTY_FIPS_CODE,EPEST_LOW_KG,EPEST_HIGH_KG
0,1-METHYL CYCLOPROPENE,2013,41,1,NaN,0.0
1,1-METHYL CYCLOPROPENE,2013,41,21,NaN,0.0
2,1-METHYL CYCLOPROPENE,2013,41,27,NaN,0.2
3,1-METHYL CYCLOPROPENE,2013,41,49,NaN,0.0
4,1-METHYL CYCLOPROPENE,2013,41,55,NaN,0.0

In [5]:
site_info.head()

,Location_Identifier,station_nm,Site_Abb,AggRegion_nam,Region_nam,state_cd,huc_cd,Drainage_area_km2,dec_lat_va,dec_long_va,dec_coord_datum_cd
0,USGS-06713500,"CHERRY CREEK AT DENVER, CO.","Cherry Creek, CO",High Plains,Central High Plains,8,10190003,1062.0,39.742487,-104.999982,NAD83
1,USGS-06754000,"SOUTH PLATTE RIVER NEAR KERSEY, CO","S. Platte R, CO",High Plains,Central High Plains,8,10190003,25022.0,40.411925,-104.562737,NAD83
2,USGS-06805500,"Platte River at Louisville, Nebr","Platte R, NE",High Plains,Central High Plains,31,10200202,221107.0,41.014978,-96.157500,NAD83
3,USGS-06329500,Yellowstone River near Sidney MT,"Yellow. R, MT",High Plains,Northern High Plains,30,10100004,178966.0,47.677414,-104.155411,NAD83
4,USGS-07144100,"L ARKANSAS R NR SEDGWICK, KS","Lit. Arkans. R, KS",High Plains,Southern High Plains,20,11030012,3209.0,37.883067,-97.424486,NAD83

In [6]:
pest_water.head()

,Pesticide_Site,Pesticide_Name,Site_Abb,USGSpcode,Water_Year,Activity_StartDate,Activity_StartTime,Activity_StartTimeZone,Activity_MediaSubdivision,Activity_TypeCode,LabInfo_Name,Activity_ActivityIdentifier,Result_ResultDetectionCondition,Result_Value_ug_L
0,"1H-1,2,4-Triazole_01184000","1H-1,2,4-Triazole","Conn. R, CT",68498,2013,2012-10-16,09:30:00,EST,Surface water,"Sample - Routine, regular","USGS-National Water Quality Lab, Denver, CO",821ef99f-9a4e-4159-9ce1-594cfdc22444,Not Detected,0.0262
1,"1H-1,2,4-Triazole_01184000","1H-1,2,4-Triazole","Conn. R, CT",68498,2013,2012-11-20,10:30:00,EST,Surface water,"Sample - Routine, regular","USGS-National Water Quality Lab, Denver, CO",8d1cd0e7-d2b7-45f5-b741-5d58c219e652,Not Detected,0.0486
2,"1H-1,2,4-Triazole_01184000","1H-1,2,4-Triazole","Conn. R, CT",68498,2013,2012-12-17,11:10:00,EST,Surface water,"Sample - Routine, regular","USGS-National Water Quality Lab, Denver, CO",eb5141c4-2a10-4fc0-a798-5a1ea2496526,Not Detected,0.0391
3,"1H-1,2,4-Triazole_01184000","1H-1,2,4-Triazole","Conn. R, CT",68498,2013,2013-01-18,08:50:00,EST,Surface water,"Sample - Routine, regular","USGS-National Water Quality Lab, Denver, CO",7d065dd6-1786-405f-8fe5-210ac4e6a42b,Not Detected,0.0220
4,"1H-1,2,4-Triazole_01184000","1H-1,2,4-Triazole","Conn. R, CT",68498,2013,2013-02-04,10:30:00,EST,Surface water,"Sample - Routine, regular","USGS-National Water Quality Lab, Denver, CO",7e8fe5a8-d053-4f1e-bd8e-f25f9d20445d,Not Detected,0.0803

In [ ]:
print(pest_use.shape)
print(site_info.shape)
print(pest_water.shape)

(2004805, 6)
(82, 11)
                          Pesticide_Site     Pesticide_Name         Site_Abb  \
0             1H-1,2,4-Triazole_01184000  1H-1,2,4-Triazole      Conn. R, CT
1             1H-1,2,4-Triazole_01184000  1H-1,2,4-Triazole      Conn. R, CT
2             1H-1,2,4-Triazole_01184000  1H-1,2,4-Triazole      Conn. R, CT
3             1H-1,2,4-Triazole_01184000  1H-1,2,4-Triazole      Conn. R, CT
4             1H-1,2,4-Triazole_01184000  1H-1,2,4-Triazole      Conn. R, CT
...                                  ...                ...              ...
955723  trans-Permethrin_394340085524601   trans-Permethrin  Sugar Creek, IN
955724  trans-Permethrin_394340085524601   trans-Permethrin  Sugar Creek, IN
955725  trans-Permethrin_394340085524601   trans-Permethrin  Sugar Creek, IN
955726  trans-Permethrin_394340085524601   trans-Permethrin  Sugar Creek, IN
955727  trans-Permethrin_394340085524601   trans-Permethrin  Sugar Creek, IN

        USGSpcode  Water_Year Activity_StartDate Activity_StartTime  \
0           68498        2013         2012-10-16           09:30:00
1           68498        2013         2012-11-20           10:30:00
2           68498        2013         2012-12-17           11:10:00
3           68498        2013         2013-01-18           08:50:00
4           68498        2013         2013-02-04           10:30:00
...           ...         ...                ...                ...
955723      68708        2022         2022-08-03           10:30:00
955724      68708        2022         2022-08-16           08:20:00
955725      68708        2022         2022-08-29           08:10:00
955726      68708        2022         2022-09-06           08:20:00
955727      68708        2022         2022-09-21           08:10:00

       Activity_StartTimeZone Activity_MediaSubdivision  \
0                         EST             Surface water
1                         EST             Surface water
2                         EST             Surface water
3                         EST             Surface water
4                         EST             Surface water
...                       ...                       ...
955723                    EST             Surface water
955724                    EST             Surface water
955725                    EST             Surface water
955726                    EST             Surface water
955727                    EST             Surface water

                Activity_TypeCode  \
0       Sample - Routine, regular
1       Sample - Routine, regular
2       Sample - Routine, regular
3       Sample - Routine, regular
4       Sample - Routine, regular
...                           ...
955723  Sample - Routine, regular
955724  Sample - Routine, regular
955725  Sample - Routine, regular
955726  Sample - Routine, regular
955727  Sample - Routine, regular

                                       LabInfo_Name  \
0       USGS-National Water Quality Lab, Denver, CO
1       USGS-National Water Quality Lab, Denver, CO
2       USGS-National Water Quality Lab, Denver, CO
3       USGS-National Water Quality Lab, Denver, CO
4       USGS-National Water Quality Lab, Denver, CO
...                                             ...
955723  USGS-National Water Quality Lab, Denver, CO
955724  USGS-National Water Quality Lab, Denver, CO
955725  USGS-National Water Quality Lab, Denver, CO
955726  USGS-National Water Quality Lab, Denver, CO
955727  USGS-National Water Quality Lab, Denver, CO

                 Activity_ActivityIdentifier Result_ResultDetectionCondition  \
0       821ef99f-9a4e-4159-9ce1-594cfdc22444                    Not Detected
1       8d1cd0e7-d2b7-45f5-b741-5d58c219e652                    Not Detected
2       eb5141c4-2a10-4fc0-a798-5a1ea2496526                    Not Detected
3       7d065dd6-1786-405f-8fe5-210ac4e6a42b                    Not Detected
4       7e8fe5a8-d053-4f1e-bd8e-f25f9d20445d                    Not Detected
...                                      ...                             ...
955723  4a3da07c-1d34-4ea6-abe1-4974636a6974                    Not Detected
955724  80fd1536-d041-47f5-9fe8-50094600780e                    Not Detected
955725  838afda1-8d49-4cd2-a5ba-fac72f2d0d7a                    Not Detected
955726  4402881e-d88c-460c-848f-d22cc5c3f65b                    Not Detected
955727  f478023c-422e-4dc0-847f-9b09b3d02e79                    Not Detected

        Result_Value_ug_L
0                  0.0262
1                  0.0486
2                  0.0391
3                  0.0220
4                  0.0803
...                   ...
955723             0.0038
955724             0.0100
955725             0.0038
955726             0.0038
955727             0.0038

[955728 rows x 14 columns]

In [8]:
pest_use.info()

<class 'pandas.DataFrame'>
RangeIndex: 2004805 entries, 0 to 2004804
Data columns (total 6 columns):
 #   Column            Dtype
---  ------            -----
 0   COMPOUND          str
 1   YEAR              int64
 2   STATE_FIPS_CODE   int64
 3   COUNTY_FIPS_CODE  int64
 4   EPEST_LOW_KG      float64
 5   EPEST_HIGH_KG     float64
dtypes: float64(2), int64(3), str(1)
memory usage: 91.8 MB

In [9]:
site_info.info()

<class 'pandas.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Location_Identifier  82 non-null     str
 1   station_nm           82 non-null     str
 2   Site_Abb             82 non-null     str
 3   AggRegion_nam        82 non-null     str
 4   Region_nam           82 non-null     str
 5   state_cd             82 non-null     int64
 6   huc_cd               82 non-null     int64
 7   Drainage_area_km2    80 non-null     float64
 8   dec_lat_va           82 non-null     float64
 9   dec_long_va          82 non-null     float64
 10  dec_coord_datum_cd   82 non-null     str
dtypes: float64(3), int64(2), str(6)
memory usage: 7.2 KB

In [10]:
pest_water.info()

<class 'pandas.DataFrame'>
RangeIndex: 955728 entries, 0 to 955727
Data columns (total 14 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Pesticide_Site                   955728 non-null  str
 1   Pesticide_Name                   955728 non-null  str
 2   Site_Abb                         955728 non-null  str
 3   USGSpcode                        955728 non-null  int64
 4   Water_Year                       955728 non-null  int64
 5   Activity_StartDate               955728 non-null  str
 6   Activity_StartTime               955728 non-null  str
 7   Activity_StartTimeZone           955728 non-null  str
 8   Activity_MediaSubdivision        955728 non-null  str
 9   Activity_TypeCode                955728 non-null  str
 10  LabInfo_Name                     955727 non-null  str
 11  Activity_ActivityIdentifier      955728 non-null  str
 12  Result_ResultDetectionCondition  749158 non-null  str
 13  Result_Value_ug_L                955728 non-null  float64
dtypes: float64(1), int64(2), str(11)
memory usage: 102.1 MB

In [11]:
pest_use.describe()

,YEAR,STATE_FIPS_CODE,COUNTY_FIPS_CODE,EPEST_LOW_KG,EPEST_HIGH_KG
count,2.004805e+06,2.004805e+06,2.004805e+06,1.363143e+06,2.004805e+06
mean,2.014925e+03,3.062408e+01,9.553804e+01,1.702369e+03,1.327162e+03
std,1.413883e+00,1.484951e+01,8.628876e+01,2.200232e+04,1.854794e+04
min,2.013000e+03,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00
25%,2.014000e+03,1.800000e+01,3.500000e+01,1.200000e+00,1.800000e+00
50%,2.015000e+03,2.900000e+01,7.700000e+01,1.420000e+01,1.800000e+01
75%,2.016000e+03,4.500000e+01,1.310000e+02,1.506000e+02,1.491000e+02
max,2.017000e+03,5.600000e+01,8.100000e+02,5.569201e+06,5.569201e+06

In [12]:
site_info.describe()

        state_cd        huc_cd  Drainage_area_km2  dec_lat_va  dec_long_va
count  82.000000  8.200000e+01       8.000000e+01   82.000000    82.000000
mean   25.634146  8.783280e+06       2.203832e+05   38.246760   -95.071958
std    14.481587  5.164852e+06       5.299429e+05    5.020849    14.084326
min     1.000000  1.080205e+06       3.900000e+01   25.876748  -123.183454
25%    16.250000  4.112584e+06       3.871250e+03   33.900984  -104.460905
50%    22.000000  8.030208e+06       3.482750e+04   38.940357   -91.417223
75%    37.000000  1.206010e+07       1.267620e+05   41.545888   -86.907279
max    53.000000  1.807020e+07       2.929652e+06   47.926923   -72.605367

In [13]:
pest_water.describe()

           USGSpcode     Water_Year  Result_Value_ug_L
count  955728.000000  955728.000000      955728.000000
mean    67534.097277    2017.251536           0.069224
std      1702.079453       2.831645           0.495428
min     61680.000000    2013.000000           0.000010
25%     66613.000000    2015.000000           0.004000
50%     68547.000000    2017.000000           0.007000
75%     68647.000000    2020.000000           0.025000
max     68873.000000    2022.000000         137.000000

In [14]:
missing_percent = pest_water.isna().mean().sort_values(ascending=False) * 100
missing_percent

Result_ResultDetectionCondition    21.613890
LabInfo_Name                        0.000105
Site_Abb                            0.000000
USGSpcode                           0.000000
Pesticide_Site                      0.000000
Pesticide_Name                      0.000000
Activity_StartDate                  0.000000
Water_Year                          0.000000
Activity_StartTime                  0.000000
Activity_StartTimeZone              0.000000
Activity_TypeCode                   0.000000
Activity_MediaSubdivision           0.000000
Activity_ActivityIdentifier         0.000000
Result_Value_ug_L                   0.000000
dtype: float64

In [15]:
missing_percent = pest_use.isna().mean().sort_values(ascending=False) * 100
missing_percent

EPEST_LOW_KG        32.006205
COMPOUND             0.000000
YEAR                 0.000000
STATE_FIPS_CODE      0.000000
COUNTY_FIPS_CODE     0.000000
EPEST_HIGH_KG        0.000000
dtype: float64

In [16]:
missing_percent = site_info.isna().mean().sort_values(ascending=False) * 100
missing_percent

Drainage_area_km2      2.439024
station_nm             0.000000
Location_Identifier    0.000000
Site_Abb               0.000000
AggRegion_nam          0.000000
state_cd               0.000000
Region_nam             0.000000
huc_cd                 0.000000
dec_lat_va             0.000000
dec_long_va            0.000000
dec_coord_datum_cd     0.000000
dtype: float64

# Data Cleaning

### Cleaning Columns

In [18]:
#Pesticide Use Data 
pest_use = pest_use.loc[:,['COMPOUND', 'YEAR', 'STATE_FIPS_CODE', 'COUNTY_FIPS_CODE', 'EPEST_HIGH_KG']]

In [24]:
#Water Pesticide Concentration Data 
pest_water = pest_water.loc[:,['Pesticide_Site', 'Pesticide_Name','Water_Year', 'Result_Value_ug_L']]

In [27]:
#Site Info 
site_info = site_info.loc[:,['Location_Identifier', 'station_nm','state_cd', 'huc_cd',	'Drainage_area_km2','dec_lat_va','dec_long_va']]

### Fixing Column Types

In [31]:
# Pesticide Use Compounds 
pest_use['Year'] = pd.to_datetime(pest_use['YEAR'], format='%Y')
pest_use["STATE_FIPS_CODE"] = pest_use["STATE_FIPS_CODE"].astype("category")
pest_use["COUNTY_FIPS_CODE"] = pest_use["COUNTY_FIPS_CODE"].astype("category")

/tmp/ipykernel_6086/1143327603.py:2: Pandas4Warning: Parsing integer or float values with a format in to_datetime is deprecated. In a future version these will be interpreted as epochs via the 'unit' keyword instead. Cast them to strings first to retain the current behavior.
  pest_use['Year'] = pd.to_datetime(pest_use['YEAR'], format='%Y')

In [36]:
# Water Pesticide Data 
pest_water['Year'] = pd.to_datetime(pest_water['Water_Year'], format='%Y')

/tmp/ipykernel_6086/3867290275.py:2: Pandas4Warning: Parsing integer or float values with a format in to_datetime is deprecated. In a future version these will be interpreted as epochs via the 'unit' keyword instead. Cast them to strings first to retain the current behavior.
  pest_water['Year'] = pd.to_datetime(pest_water['Water_Year'], format='%Y')

In [42]:
# Site Information 
site_info["huc_cd"] = site_info["huc_cd"].astype("category")
site_info["state_cd"] = site_info["state_cd"].astype("category")

# Joining Data Frames

### Site Location Data with Water Samples

In [ ]:
#Taking out USGS from Location Identity to help match with Water data 
site_info["site_id"] = site_info["Location_Identifier"].str.replace("USGS-", "")
site_info.head()

,Location_Identifier,station_nm,state_cd,huc_cd,Drainage_area_km2,dec_lat_va,dec_long_va,site_id
0,USGS-06713500,"CHERRY CREEK AT DENVER, CO.",8,10190003,1062.0,39.742487,-104.999982,06713500
1,USGS-06754000,"SOUTH PLATTE RIVER NEAR KERSEY, CO",8,10190003,25022.0,40.411925,-104.562737,06754000
2,USGS-06805500,"Platte River at Louisville, Nebr",31,10200202,221107.0,41.014978,-96.157500,06805500
3,USGS-06329500,Yellowstone River near Sidney MT,30,10100004,178966.0,47.677414,-104.155411,06329500
4,USGS-07144100,"L ARKANSAS R NR SEDGWICK, KS",20,11030012,3209.0,37.883067,-97.424486,07144100

In [51]:
#Get water pesticide location without starting name 
pest_water["site_id"] = pest_water["Pesticide_Site"].str.split("_").str[1]
pest_water.head()

,Pesticide_Site,Pesticide_Name,Water_Year,Result_Value_ug_L,Year,pesticide,site_id
0,"1H-1,2,4-Triazole_01184000","1H-1,2,4-Triazole",2013,0.0262,2013-01-01,"1H-1,2,4-Triazole",01184000
1,"1H-1,2,4-Triazole_01184000","1H-1,2,4-Triazole",2013,0.0486,2013-01-01,"1H-1,2,4-Triazole",01184000
2,"1H-1,2,4-Triazole_01184000","1H-1,2,4-Triazole",2013,0.0391,2013-01-01,"1H-1,2,4-Triazole",01184000
3,"1H-1,2,4-Triazole_01184000","1H-1,2,4-Triazole",2013,0.0220,2013-01-01,"1H-1,2,4-Triazole",01184000
4,"1H-1,2,4-Triazole_01184000","1H-1,2,4-Triazole",2013,0.0803,2013-01-01,"1H-1,2,4-Triazole",01184000

In [54]:
#Left Join using pest_water using site_id column 
pest_water_loc = (
    pest_water
    .join(
        site_info.set_index('site_id'),
        on='site_id',
        how='left'
    )
    .drop(columns=['Pesticide_Site', 'Location_Identifier'])
)
pest_water_loc.head()

,Pesticide_Name,Water_Year,Result_Value_ug_L,Year,pesticide,site_id,station_nm,state_cd,huc_cd,Drainage_area_km2,dec_lat_va,dec_long_va
0,"1H-1,2,4-Triazole",2013,0.0262,2013-01-01,"1H-1,2,4-Triazole",01184000,"CONNECTICUT RIVER AT THOMPSONVILLE, CT",9,1080205,25019.0,41.987319,-72.605367
1,"1H-1,2,4-Triazole",2013,0.0486,2013-01-01,"1H-1,2,4-Triazole",01184000,"CONNECTICUT RIVER AT THOMPSONVILLE, CT",9,1080205,25019.0,41.987319,-72.605367
2,"1H-1,2,4-Triazole",2013,0.0391,2013-01-01,"1H-1,2,4-Triazole",01184000,"CONNECTICUT RIVER AT THOMPSONVILLE, CT",9,1080205,25019.0,41.987319,-72.605367
3,"1H-1,2,4-Triazole",2013,0.0220,2013-01-01,"1H-1,2,4-Triazole",01184000,"CONNECTICUT RIVER AT THOMPSONVILLE, CT",9,1080205,25019.0,41.987319,-72.605367
4,"1H-1,2,4-Triazole",2013,0.0803,2013-01-01,"1H-1,2,4-Triazole",01184000,"CONNECTICUT RIVER AT THOMPSONVILLE, CT",9,1080205,25019.0,41.987319,-72.605367